# ==============================================================================
# Merged Lakeflow Source: actitime
# ==============================================================================
# This file is auto-generated by tools/scripts/merge_python_source.py
# Do not edit manually. Make changes to the source files instead.
# ==============================================================================

from datetime import datetime, timedelta
from decimal import Decimal
from typing import (
    Any,
    Dict,
    Iterator,
    List,
    Tuple,
)
import json
import time

from pyspark.sql import Row
from pyspark.sql.datasource import DataSource, DataSourceReader, SimpleDataSourceStreamReader
from pyspark.sql.types import *
import base64
import random
import requests


def register_lakeflow_source(spark):
    """Register the Lakeflow Python source with Spark."""

    ########################################################
    # libs/utils.py
    ########################################################

    def _parse_struct(value: Any, field_type: StructType) -> Row:
        """Parse a dictionary into a PySpark Row based on StructType schema."""
        if not isinstance(value, dict):
            raise ValueError(f"Expected a dictionary for StructType, got {type(value)}")
        # Spark Python -> Arrow conversion require missing StructType fields to be assigned None.
        if value == {}:
            raise ValueError(
                "field in StructType cannot be an empty dict. "
                "Please assign None as the default value instead."
            )
        field_dict = {}
        for field in field_type.fields:
            if field.name in value:
                field_dict[field.name] = parse_value(value.get(field.name), field.dataType)
            elif field.nullable:
                field_dict[field.name] = None
            else:
                raise ValueError(f"Field {field.name} is not nullable but not found in the input")
        return Row(**field_dict)


    def _parse_array(value: Any, field_type: ArrayType) -> list:
        """Parse a list into a PySpark array based on ArrayType schema."""
        if not isinstance(value, list):
            if field_type.containsNull:
                return [parse_value(value, field_type.elementType)]
            raise ValueError(f"Expected a list for ArrayType, got {type(value)}")
        return [parse_value(v, field_type.elementType) for v in value]


    def _parse_map(value: Any, field_type: MapType) -> dict:
        """Parse a dictionary into a PySpark map based on MapType schema."""
        if not isinstance(value, dict):
            raise ValueError(f"Expected a dictionary for MapType, got {type(value)}")
        return {
            parse_value(k, field_type.keyType): parse_value(v, field_type.valueType)
            for k, v in value.items()
        }


    def _parse_string(value: Any) -> str:
        """Convert value to string."""
        return str(value)


    def _parse_integer(value: Any) -> int:
        """Convert value to integer."""
        if isinstance(value, str) and value.strip():
            return int(float(value)) if "." in value else int(value)
        if isinstance(value, (int, float)):
            return int(value)
        raise ValueError(f"Cannot convert {value} to integer")


    def _parse_float(value: Any) -> float:
        """Convert value to float."""
        return float(value)


    def _parse_decimal(value: Any) -> Decimal:
        """Convert value to Decimal."""
        return Decimal(value) if isinstance(value, str) and value.strip() else Decimal(str(value))


    def _parse_boolean(value: Any) -> bool:
        """Convert value to boolean."""
        if isinstance(value, str):
            lowered = value.lower()
            if lowered in ("true", "t", "yes", "y", "1"):
                return True
            if lowered in ("false", "f", "no", "n", "0"):
                return False
        return bool(value)


    def _parse_date(value: Any) -> datetime.date:
        """Convert value to date."""
        if isinstance(value, str):
            for fmt in ("%Y-%m-%d", "%m/%d/%Y", "%d-%m-%Y", "%Y/%m/%d"):
                try:
                    return datetime.strptime(value, fmt).date()
                except ValueError:
                    continue
            return datetime.fromisoformat(value).date()
        if isinstance(value, datetime):
            return value.date()
        raise ValueError(f"Cannot convert {value} to date")


    def _parse_timestamp(value: Any) -> datetime:
        """Convert value to timestamp."""
        if isinstance(value, str):
            ts_value = value.replace("Z", "+00:00") if value.endswith("Z") else value
            try:
                return datetime.fromisoformat(ts_value)
            except ValueError:
                for fmt in ("%Y-%m-%d %H:%M:%S", "%Y/%m/%d %H:%M:%S"):
                    try:
                        return datetime.strptime(ts_value, fmt)
                    except ValueError:
                        continue
        elif isinstance(value, (int, float)):
            return datetime.fromtimestamp(value)
        elif isinstance(value, datetime):
            return value
        raise ValueError(f"Cannot convert {value} to timestamp")


    def _decode_string_to_bytes(value: str) -> bytes:
        """Try to decode a string as base64, then hex, then UTF-8."""
        try:
            return base64.b64decode(value)
        except Exception:
            pass
        try:
            return bytes.fromhex(value)
        except Exception:
            pass
        return value.encode("utf-8")


    def _parse_binary(value: Any) -> bytes:
        """Convert value to bytes. Tries base64, then hex, then UTF-8 for strings."""
        if isinstance(value, bytes):
            return value
        if isinstance(value, bytearray):
            return bytes(value)
        if isinstance(value, str):
            return _decode_string_to_bytes(value)
        if isinstance(value, list):
            return bytes(value)
        return str(value).encode("utf-8")


    # Mapping of primitive types to their parser functions
    _PRIMITIVE_PARSERS = {
        StringType: _parse_string,
        IntegerType: _parse_integer,
        LongType: _parse_integer,
        FloatType: _parse_float,
        DoubleType: _parse_float,
        DecimalType: _parse_decimal,
        BooleanType: _parse_boolean,
        DateType: _parse_date,
        TimestampType: _parse_timestamp,
        BinaryType: _parse_binary,
    }


    def parse_value(value: Any, field_type: DataType) -> Any:
        """
        Converts a JSON value into a PySpark-compatible data type based on the provided field type.
        """
        if value is None:
            return None

        # Handle complex types
        if isinstance(field_type, StructType):
            return _parse_struct(value, field_type)
        if isinstance(field_type, ArrayType):
            return _parse_array(value, field_type)
        if isinstance(field_type, MapType):
            return _parse_map(value, field_type)

        # Handle primitive types via type-based lookup
        try:
            field_type_class = type(field_type)
            if field_type_class in _PRIMITIVE_PARSERS:
                return _PRIMITIVE_PARSERS[field_type_class](value)

            # Check for custom UDT handling
            if hasattr(field_type, "fromJson"):
                return field_type.fromJson(value)

            raise TypeError(f"Unsupported field type: {field_type}")
        except (ValueError, TypeError) as e:
            raise ValueError(f"Error converting '{value}' ({type(value)}) to {field_type}: {str(e)}")


    ########################################################
    # sources/actitime/actitime.py
    ########################################################

    class ActitimeAPIError(Exception):
        """Custom exception for actiTIME API errors with structured information."""

        def __init__(self, status_code: int, key: str, message: str, url: str):
            """
            Initialize the exception.

            Args:
                status_code: HTTP status code
                key: Error key from actiTIME (e.g., "api.error.customer_exists")
                message: Human-readable error message
                url: The URL that caused the error
            """
            self.status_code = status_code
            self.key = key
            self.message = message
            self.url = url
            super().__init__(
                f"actiTIME API Error [{status_code}] at {url}: {key} - {message}"
            )

        @classmethod
        def from_response(
            cls, response: requests.Response, url: str
        ) -> "ActitimeAPIError":
            """
            Factory method to create error from response.

            Args:
                response: The HTTP response object
                url: The URL that was called

            Returns:
                ActitimeAPIError instance
            """
            try:
                error_data = response.json()
                key = error_data.get("key", "unknown_error")
                message = error_data.get("message", response.text)
            except Exception:
                key = "parse_error"
                message = response.text[:500] if response.text else "No response body"

            return cls(response.status_code, key, message, url)


    class RateLimiter:
        """
        Rate limiter for actiTIME API with per-second and per-minute limits.

        actiTIME enforces:
        - 100 requests per second per user account
        - 1000 requests per minute per user account
        - IP ban after 3 failed auth attempts in 10 seconds
        """

        def __init__(
            self, requests_per_second: int = 100, requests_per_minute: int = 1000
        ):
            """
            Initialize the rate limiter.

            Args:
                requests_per_second: Maximum requests per second (default: 100)
                requests_per_minute: Maximum requests per minute (default: 1000)
            """
            self.requests_per_second = requests_per_second
            self.requests_per_minute = requests_per_minute
            self._request_timestamps: List[float] = []
            self._last_request_time: float = 0

        def wait_if_needed(self) -> None:
            """Enforce rate limiting by sleeping if needed."""
            now = time.time()

            # Enforce minimum delay between requests (10ms for 100 req/sec)
            min_delay = 1.0 / self.requests_per_second
            time_since_last = now - self._last_request_time
            if time_since_last < min_delay:
                time.sleep(min_delay - time_since_last)
                now = time.time()

            # Clean up timestamps older than 1 minute
            self._request_timestamps = [
                ts for ts in self._request_timestamps if now - ts < 60
            ]

            # If at minute limit, wait for oldest request to expire
            if len(self._request_timestamps) >= self.requests_per_minute:
                sleep_time = 60 - (now - self._request_timestamps[0])
                if sleep_time > 0:
                    time.sleep(sleep_time)

            self._request_timestamps.append(time.time())
            self._last_request_time = time.time()


    class LakeflowConnect:
        """
        actiTIME connector implementing the Lakeflow Connect interface.

        This connector provides access to actiTIME data for time tracking,
        project management, and user management.

        Connection Options (required):
            - base_url: actiTIME instance URL (e.g., https://your-company.actitime.com)
            - username: actiTIME username
            - password: actiTIME password

        Supported Tables (13 total):
            Core Business: customers, projects, tasks, timetrack, leavetime
            Users: users, departments, userRates
            Configuration: typesOfWork, leaveTypes, workflowStatuses,
                          timeZoneGroups, info (system settings)

        Note: userGroups and holidays are not available via API.
        """

        # Supported table names
        # Note: userGroups and holidays endpoints don't exist in actiTIME API
        # settings endpoint is actually /info
        SUPPORTED_TABLES = [
            "customers",
            "projects",
            "tasks",
            "timetrack",
            "leavetime",
            "users",
            "departments",
            "userRates",
            "typesOfWork",
            "leaveTypes",
            "workflowStatuses",
            "timeZoneGroups",
            "info",  # System settings - was incorrectly named "settings"
        ]

        def __init__(self, options: Dict[str, str]) -> None:
            """
            Initialize the actiTIME connector.

            Args:
                options: Dictionary containing connection options:
                    - base_url (required): actiTIME instance URL
                    - username (required): actiTIME username
                    - password (required): actiTIME password

            Raises:
                ValueError: If required options are missing
            """
            # Validate required options
            base_url = options.get("base_url")
            username = options.get("username")
            password = options.get("password")

            if not base_url:
                raise ValueError(
                    "actiTIME connector requires 'base_url' in options"
                )
            if not username:
                raise ValueError(
                    "actiTIME connector requires 'username' in options"
                )
            if not password:
                raise ValueError(
                    "actiTIME connector requires 'password' in options"
                )

            # Store configuration
            self.base_url = base_url.rstrip("/") + "/api/v1"

            # Build auth header (Basic Authentication)
            credentials = f"{username}:{password}"
            encoded = base64.b64encode(credentials.encode()).decode()

            # Configure session with proper headers
            self._session = requests.Session()
            self._session.headers.update(
                {
                    "Authorization": f"Basic {encoded}",
                    "Accept": "application/json; charset=UTF-8",
                    "Content-Type": "application/json; charset=UTF-8",
                }
            )

            # Initialize rate limiter
            self._rate_limiter = RateLimiter(
                requests_per_second=100, requests_per_minute=1000
            )

            # Auth failure tracking to prevent IP ban
            self._auth_failure_timestamps: List[float] = []

            # Initialize centralized table configuration (Stripe pattern)
            self._init_table_config()

            # Initialize reusable schema components
            self._init_schema_components()

        def _init_table_config(self) -> None:
            """Initialize centralized table configuration."""
            self._table_config = {
                "customers": {
                    "primary_keys": ["id"],
                    "cursor_field": "created",
                    "ingestion_type": "cdc",
                    "endpoint": "customers",
                    "supports_pagination": True,
                    "supports_archived_filter": True,
                },
                "projects": {
                    "primary_keys": ["id"],
                    "cursor_field": "created",
                    "ingestion_type": "cdc",
                    "endpoint": "projects",
                    "supports_pagination": True,
                    "supports_archived_filter": True,
                },
                "tasks": {
                    "primary_keys": ["id"],
                    "cursor_field": "created",
                    "ingestion_type": "cdc",
                    "endpoint": "tasks",
                    "supports_pagination": True,
                    "supports_archived_filter": True,
                },
                "timetrack": {
                    "primary_keys": ["id"],
                    "cursor_field": "date",
                    "ingestion_type": "append",
                    "endpoint": "timetrack",
                    "requires_date_range": True,
                    "flatten_records": True,
                },
                "leavetime": {
                    "primary_keys": ["id"],
                    "cursor_field": "date",
                    "ingestion_type": "append",
                    "endpoint": "leavetime",
                    "requires_date_range": True,
                    "flatten_records": True,
                },
                "users": {
                    "primary_keys": ["id"],
                    "cursor_field": "created",
                    "ingestion_type": "cdc",
                    "endpoint": "users",
                    "supports_pagination": True,
                },
                "departments": {
                    "primary_keys": ["id"],
                    "ingestion_type": "snapshot",
                    "endpoint": "departments",
                },
                "userRates": {
                    "primary_keys": ["userId", "dateFrom"],
                    "ingestion_type": "snapshot",
                    "endpoint": "userRates",
                    "parent_child": True,
                },
                "typesOfWork": {
                    "primary_keys": ["id"],
                    "ingestion_type": "snapshot",
                    "endpoint": "typesOfWork",
                },
                "leaveTypes": {
                    "primary_keys": ["id"],
                    "ingestion_type": "snapshot",
                    "endpoint": "leaveTypes",
                },
                "workflowStatuses": {
                    "primary_keys": ["id"],
                    "ingestion_type": "snapshot",
                    "endpoint": "workflowStatuses",
                },
                "timeZoneGroups": {
                    "primary_keys": ["id"],
                    "ingestion_type": "snapshot",
                    "endpoint": "timeZoneGroups",
                },
                "info": {
                    "primary_keys": ["id"],
                    "ingestion_type": "snapshot",
                    "endpoint": "info",
                    "singleton": True,
                },
            }

        def _init_schema_components(self) -> None:
            """Initialize reusable schema components."""
            # Standard allowed actions schema (customers, projects)
            self._allowed_actions_schema = StructType(
                [
                    StructField("canModify", BooleanType(), True),
                    StructField("canDelete", BooleanType(), True),
                ]
            )

            # Extended allowed actions schema (tasks)
            self._task_allowed_actions_schema = StructType(
                [
                    StructField("canModify", BooleanType(), True),
                    StructField("canDelete", BooleanType(), True),
                    StructField("canComplete", BooleanType(), True),
                ]
            )

        # =========================================================================
        # Public Interface Methods
        # =========================================================================

        def list_tables(self) -> List[str]:
            """
            List names of all tables supported by this connector.

            Returns:
                List of supported table names
            """
            return self.SUPPORTED_TABLES.copy()

        def get_table_schema(
            self, table_name: str, table_options: Dict[str, str]
        ) -> StructType:
            """
            Get the Spark schema for a table.

            Args:
                table_name: Name of the table
                table_options: Additional options (unused for static schemas)

            Returns:
                StructType representing the table schema

            Raises:
                ValueError: If table_name is not supported
            """
            if table_name not in self.SUPPORTED_TABLES:
                raise ValueError(
                    f"Table '{table_name}' is not supported. "
                    f"Supported tables: {self.SUPPORTED_TABLES}"
                )

            schema_methods = {
                "customers": self._get_customers_schema,
                "projects": self._get_projects_schema,
                "tasks": self._get_tasks_schema,
                "timetrack": self._get_timetrack_schema,
                "leavetime": self._get_leavetime_schema,
                "users": self._get_users_schema,
                "departments": self._get_departments_schema,
                "userRates": self._get_user_rates_schema,
                "typesOfWork": self._get_types_of_work_schema,
                "leaveTypes": self._get_leave_types_schema,
                "workflowStatuses": self._get_workflow_statuses_schema,
                "timeZoneGroups": self._get_time_zone_groups_schema,
                "info": self._get_info_schema,
            }

            return schema_methods[table_name]()

        def read_table_metadata(
            self, table_name: str, table_options: Dict[str, str]
        ) -> Dict[str, Any]:
            """
            Get metadata for a table.

            Args:
                table_name: Name of the table
                table_options: Additional options (unused)

            Returns:
                Dictionary with primary_keys, cursor_field (optional),
                and ingestion_type

            Raises:
                ValueError: If table_name is not supported
            """
            if table_name not in self.SUPPORTED_TABLES:
                raise ValueError(
                    f"Table '{table_name}' is not supported. "
                    f"Supported tables: {self.SUPPORTED_TABLES}"
                )

            config = self._table_config[table_name]
            metadata = {
                "primary_keys": config["primary_keys"],
                "ingestion_type": config["ingestion_type"],
            }

            if "cursor_field" in config:
                metadata["cursor_field"] = config["cursor_field"]

            return metadata

        def read_table(
            self,
            table_name: str,
            start_offset: Dict[str, Any],
            table_options: Dict[str, str],
        ) -> Tuple[Iterator[Dict[str, Any]], Dict[str, Any]]:
            """
            Read records from a table.

            Args:
                table_name: Name of the table to read
                start_offset: Cursor position for incremental reads
                table_options: Table-specific options (e.g., dateFrom, dateTo)

            Returns:
                Tuple of (records iterator, new offset for next sync)

            Raises:
                ValueError: If table_name is not supported or required options missing
            """
            if table_name not in self.SUPPORTED_TABLES:
                raise ValueError(
                    f"Table '{table_name}' is not supported. "
                    f"Supported tables: {self.SUPPORTED_TABLES}"
                )

            reader_map = {
                "customers": self._read_customers,
                "projects": self._read_projects,
                "tasks": self._read_tasks,
                "timetrack": self._read_timetrack,
                "leavetime": self._read_leavetime,
                "users": self._read_users,
                "departments": self._read_departments,
                "userRates": self._read_user_rates,
                "typesOfWork": self._read_types_of_work,
                "leaveTypes": self._read_leave_types,
                "workflowStatuses": self._read_workflow_statuses,
                "timeZoneGroups": self._read_time_zone_groups,
                "info": self._read_info,
            }

            return reader_map[table_name](start_offset, table_options)

        def test_connection(self) -> Dict[str, str]:
            """
            Test the connection to actiTIME API.

            Returns:
                Dictionary with status and message:
                - {"status": "success", "message": "Connection successful"}
                - {"status": "error", "message": "Error details..."}
            """
            try:
                # Use a lightweight endpoint to test connectivity
                url = f"{self.base_url}/settings"
                response = self._make_request_with_retry("GET", url)

                if response.status_code == 200:
                    return {"status": "success", "message": "Connection successful"}
                elif response.status_code == 401:
                    return {
                        "status": "error",
                        "message": "Authentication failed: Invalid credentials",
                    }
                elif response.status_code == 403:
                    return {
                        "status": "error",
                        "message": "Authorization failed: Insufficient permissions",
                    }
                else:
                    return {
                        "status": "error",
                        "message": f"API error: {response.status_code} {response.text}",
                    }
            except Exception as e:
                return {"status": "error", "message": f"Connection failed: {str(e)}"}

        # =========================================================================
        # Schema Definitions
        # =========================================================================

        def _get_customers_schema(self) -> StructType:
            """Return schema for customers table."""
            return StructType(
                [
                    StructField("id", LongType(), False),
                    StructField("name", StringType(), True),
                    StructField("description", StringType(), True),
                    StructField("archived", BooleanType(), True),
                    StructField("created", LongType(), True),
                    StructField("url", StringType(), True),
                    StructField("allowedActions", self._allowed_actions_schema, True),
                ]
            )

        def _get_projects_schema(self) -> StructType:
            """Return schema for projects table."""
            return StructType(
                [
                    StructField("id", LongType(), False),
                    StructField("name", StringType(), True),
                    StructField("description", StringType(), True),
                    StructField("customerId", LongType(), True),
                    StructField("archived", BooleanType(), True),
                    StructField("created", LongType(), True),
                    StructField("workflowEnabled", BooleanType(), True),
                    StructField("defaultTypeOfWorkId", LongType(), True),
                    StructField("url", StringType(), True),
                    StructField("allowedActions", self._allowed_actions_schema, True),
                ]
            )

        def _get_tasks_schema(self) -> StructType:
            """Return schema for tasks table."""
            return StructType(
                [
                    StructField("id", LongType(), False),
                    StructField("name", StringType(), True),
                    StructField("description", StringType(), True),
                    StructField("projectId", LongType(), True),
                    StructField("customerId", LongType(), True),
                    StructField("archived", BooleanType(), True),
                    StructField("created", LongType(), True),
                    StructField("typeOfWorkId", LongType(), True),
                    StructField("workflowStatusId", LongType(), True),
                    StructField("deadline", StringType(), True),
                    StructField("estimatedTime", LongType(), True),
                    StructField("url", StringType(), True),
                    StructField(
                        "allowedActions", self._task_allowed_actions_schema, True
                    ),
                ]
            )

        def _get_timetrack_schema(self) -> StructType:
            """Return schema for timetrack table (flattened)."""
            return StructType(
                [
                    StructField("id", LongType(), False),
                    StructField("userId", LongType(), True),
                    StructField("date", StringType(), True),
                    StructField("taskId", LongType(), True),
                    StructField("time", LongType(), True),
                    StructField("comment", StringType(), True),
                    StructField("approved", BooleanType(), True),
                    StructField("locked", BooleanType(), True),
                    StructField("typeOfWorkId", LongType(), True),
                ]
            )

        def _get_leavetime_schema(self) -> StructType:
            """Return schema for leavetime table (flattened)."""
            return StructType(
                [
                    StructField("id", LongType(), False),
                    StructField("userId", LongType(), True),
                    StructField("date", StringType(), True),
                    StructField("leaveTypeId", LongType(), True),
                    StructField("time", LongType(), True),
                    StructField("approved", BooleanType(), True),
                ]
            )

        def _get_users_schema(self) -> StructType:
            """Return schema for users table."""
            return StructType(
                [
                    StructField("id", LongType(), False),
                    StructField("firstName", StringType(), True),
                    StructField("lastName", StringType(), True),
                    StructField("middleName", StringType(), True),
                    StructField("username", StringType(), True),
                    StructField("email", StringType(), True),
                    StructField("departmentId", LongType(), True),
                    StructField("active", BooleanType(), True),
                    StructField("created", LongType(), True),
                    StructField("timeZoneGroupId", LongType(), True),
                    StructField("userGroups", ArrayType(LongType()), True),
                    StructField("userRoles", ArrayType(StringType()), True),
                ]
            )

        def _get_departments_schema(self) -> StructType:
            """Return schema for departments table."""
            return StructType(
                [
                    StructField("id", LongType(), False),
                    StructField("name", StringType(), True),
                    StructField("description", StringType(), True),
                    StructField("parentId", LongType(), True),
                    StructField("managerId", LongType(), True),
                ]
            )

        def _get_user_rates_schema(self) -> StructType:
            """Return schema for userRates table."""
            # leaveRates is an array of {leaveTypeId, rate} objects
            leave_rate_struct = StructType(
                [
                    StructField("leaveTypeId", LongType(), True),
                    StructField("rate", DecimalType(18, 2), True),
                ]
            )
            return StructType(
                [
                    StructField("userId", LongType(), False),
                    StructField("dateFrom", StringType(), False),
                    StructField("regularRate", DecimalType(18, 2), True),
                    StructField("overtimeRate", DecimalType(18, 2), True),
                    StructField("leaveRates", ArrayType(leave_rate_struct), True),
                ]
            )

        def _get_types_of_work_schema(self) -> StructType:
            """Return schema for typesOfWork table."""
            return StructType(
                [
                    StructField("id", LongType(), False),
                    StructField("name", StringType(), True),
                    StructField("description", StringType(), True),
                    StructField("archived", BooleanType(), True),
                    StructField("billable", BooleanType(), True),
                ]
            )

        def _get_leave_types_schema(self) -> StructType:
            """Return schema for leaveTypes table."""
            return StructType(
                [
                    StructField("id", LongType(), False),
                    StructField("name", StringType(), True),
                    StructField("description", StringType(), True),
                    StructField("archived", BooleanType(), True),
                    StructField("paidLeave", BooleanType(), True),
                    StructField("autoAccrual", BooleanType(), True),
                ]
            )

        def _get_workflow_statuses_schema(self) -> StructType:
            """Return schema for workflowStatuses table."""
            return StructType(
                [
                    StructField("id", LongType(), False),
                    StructField("name", StringType(), True),
                    StructField("type", StringType(), True),
                    StructField("order", LongType(), True),
                ]
            )

        def _get_time_zone_groups_schema(self) -> StructType:
            """Return schema for timeZoneGroups table."""
            return StructType(
                [
                    StructField("id", LongType(), False),
                    StructField("name", StringType(), True),
                    StructField("timeZone", StringType(), True),
                ]
            )

        def _get_info_schema(self) -> StructType:
            """
            Return schema for info table (singleton).

            The /info endpoint returns system settings including company info,
            format settings, enabled features, URLs, and limits.
            """
            return StructType(
                [
                    StructField("id", StringType(), False),  # Synthetic PK for singleton
                    StructField("companyName", StringType(), True),
                    StructField("workdayDuration", LongType(), True),
                    StructField("weekStartDay", LongType(), True),
                    StructField("dateFormat", StringType(), True),
                    StructField("timeFormat", StringType(), True),
                    StructField("currencyCode", StringType(), True),
                    StructField("decimalSeparator", StringType(), True),
                    StructField("thousandsSeparator", StringType(), True),
                    StructField("baseUrl", StringType(), True),
                    StructField("apiVersion", StringType(), True),
                    StructField(
                        "features",
                        MapType(StringType(), BooleanType()),
                        True,
                    ),
                ]
            )

        # =========================================================================
        # HTTP Request Helpers
        # =========================================================================

        def _track_auth_failure(self) -> None:
            """Track auth failures to avoid IP ban (3 failures in 10s = 1 min ban)."""
            now = time.time()
            # Keep only failures from the last 10 seconds
            self._auth_failure_timestamps = [
                t for t in self._auth_failure_timestamps if now - t < 10
            ]
            self._auth_failure_timestamps.append(now)

            # If we have 2 failures already, preventive delay to avoid ban
            if len(self._auth_failure_timestamps) >= 2:
                time.sleep(5)

        def _check_rate_limit_headers(self, response: requests.Response) -> None:
            """Proactively slow down if rate limit headers indicate we're close."""
            remaining = response.headers.get("X-Ratelimit-Remaining")

            if remaining is not None:
                try:
                    remaining_int = int(remaining)
                    if remaining_int < 5:
                        time.sleep(1.0)
                    elif remaining_int < 10:
                        time.sleep(0.5)
                except ValueError:
                    pass

        def _make_request_with_retry(
            self,
            method: str,
            url: str,
            max_retries: int = 3,
            **kwargs: Any,
        ) -> requests.Response:
            """
            Make HTTP request with rate limiting and retry logic.

            Args:
                method: HTTP method (GET, POST, etc.)
                url: Request URL
                max_retries: Maximum number of retries on failure
                **kwargs: Additional arguments for requests

            Returns:
                Response object

            Raises:
                RuntimeError: If all retries exhausted
            """
            for attempt in range(max_retries + 1):
                # Apply rate limiting
                self._rate_limiter.wait_if_needed()

                try:
                    response = self._session.request(
                        method, url, timeout=60, **kwargs
                    )
                except requests.exceptions.RequestException as e:
                    if attempt < max_retries:
                        sleep_time = 2**attempt + random.uniform(0, 1)
                        time.sleep(sleep_time)
                        continue
                    raise RuntimeError(
                        f"Request failed after {max_retries} retries: {e}"
                    ) from e

                # Check rate limit headers for proactive throttling
                self._check_rate_limit_headers(response)

                # Handle authentication failure
                if response.status_code == 401:
                    self._track_auth_failure()
                    raise ActitimeAPIError.from_response(response, url)

                # Handle rate limiting (429)
                if response.status_code == 429:
                    retry_after = int(response.headers.get("Retry-After", 60))
                    if attempt < max_retries:
                        sleep_time = min(
                            retry_after, 2**attempt + random.uniform(0, 1)
                        )
                        time.sleep(sleep_time)
                        continue

                # Handle server errors (5xx)
                if response.status_code >= 500:
                    if attempt < max_retries:
                        sleep_time = 2**attempt + random.uniform(0, 1)
                        time.sleep(sleep_time)
                        continue

                return response

            raise RuntimeError(f"Max retries ({max_retries}) exceeded for {url}")

        # =========================================================================
        # Reader Methods - Paginated Endpoints
        # =========================================================================

        def _read_paginated(
            self,
            endpoint: str,
            start_offset: Dict[str, Any],
            table_options: Dict[str, str],
            cursor_field: str = "created",
            supports_archived: bool = False,
            supports_sort: bool = True,
        ) -> Tuple[Iterator[Dict[str, Any]], Dict[str, Any]]:
            """
            Generic reader for paginated endpoints.

            Args:
                endpoint: API endpoint name
                start_offset: Cursor for incremental reads
                table_options: Table-specific options
                cursor_field: Field to use as cursor
                supports_archived: Whether endpoint supports archived filter
                supports_sort: Whether endpoint supports sort parameter

            Returns:
                Tuple of (records iterator, new offset)
            """
            limit = int(table_options.get("limit", "100"))
            max_pages = int(table_options.get("max_pages", "100"))

            records: List[Dict[str, Any]] = []
            offset = 0
            pages_fetched = 0
            max_cursor = start_offset.get("cursor") if start_offset else None

            while pages_fetched < max_pages:
                url = f"{self.base_url}/{endpoint}"
                params: Dict[str, Any] = {
                    "offset": offset,
                    "limit": limit,
                }

                # Only add sort if supported by the endpoint
                if supports_sort and cursor_field:
                    params["sort"] = f"+{cursor_field}"

                if supports_archived:
                    params["archived"] = table_options.get("archived", "false")

                response = self._make_request_with_retry("GET", url, params=params)

                if response.status_code != 200:
                    raise ActitimeAPIError.from_response(response, url)

                data = response.json()

                # Handle both direct array and paginated response with 'items' key
                if isinstance(data, dict) and "items" in data:
                    items = data.get("items", [])
                elif isinstance(data, list):
                    items = data
                else:
                    break

                if not items:
                    break

                for record in items:
                    records.append(record)

                    # Track max cursor value
                    if cursor_field:
                        cursor_value = record.get(cursor_field)
                        if cursor_value and (
                            max_cursor is None or cursor_value > max_cursor
                        ):
                            max_cursor = cursor_value

                if len(items) < limit:
                    break

                offset += limit
                pages_fetched += 1

            next_offset = {"cursor": max_cursor} if max_cursor else {}
            return iter(records), next_offset

        def _read_customers(
            self,
            start_offset: Dict[str, Any],
            table_options: Dict[str, str],
        ) -> Tuple[Iterator[Dict[str, Any]], Dict[str, Any]]:
            """Read customers with pagination support."""
            return self._read_paginated(
                "customers",
                start_offset,
                table_options,
                cursor_field="created",
                supports_archived=True,
            )

        def _read_projects(
            self,
            start_offset: Dict[str, Any],
            table_options: Dict[str, str],
        ) -> Tuple[Iterator[Dict[str, Any]], Dict[str, Any]]:
            """Read projects with pagination support."""
            return self._read_paginated(
                "projects",
                start_offset,
                table_options,
                cursor_field="created",
                supports_archived=True,
            )

        def _read_tasks(
            self,
            start_offset: Dict[str, Any],
            table_options: Dict[str, str],
        ) -> Tuple[Iterator[Dict[str, Any]], Dict[str, Any]]:
            """Read tasks with pagination support."""
            return self._read_paginated(
                "tasks",
                start_offset,
                table_options,
                cursor_field="created",
                supports_archived=True,
            )

        def _read_users(
            self,
            start_offset: Dict[str, Any],
            table_options: Dict[str, str],
        ) -> Tuple[Iterator[Dict[str, Any]], Dict[str, Any]]:
            """Read users with pagination support (sort not supported for users)."""
            return self._read_paginated(
                "users",
                start_offset,
                table_options,
                cursor_field="",  # Users endpoint doesn't support sort by created
                supports_archived=False,
                supports_sort=False,
            )

        # =========================================================================
        # Reader Methods - Date Range Endpoints
        # =========================================================================

        def _read_timetrack(
            self,
            start_offset: Dict[str, Any],
            table_options: Dict[str, str],
        ) -> Tuple[Iterator[Dict[str, Any]], Dict[str, Any]]:
            """
            Read timetrack entries with date range filtering.

            The API returns nested structure which is flattened to individual records.

            Optional table_options:
                - dateFrom: Start date (YYYY-MM-DD). Defaults to offset cursor or 90 days ago
                - dateTo: End date (YYYY-MM-DD). Defaults to today
            """
            # Smart defaults for date range
            date_from = table_options.get("dateFrom")
            date_to = table_options.get("dateTo")

            # If not provided, use intelligent defaults
            if not date_from:
                # Use cursor from offset if available, otherwise go back 90 days
                if start_offset and "cursor" in start_offset:
                    date_from = start_offset["cursor"]
                else:
                    date_from = (datetime.now() - timedelta(days=90)).strftime("%Y-%m-%d")

            if not date_to:
                # Default to today
                date_to = datetime.now().strftime("%Y-%m-%d")

            url = f"{self.base_url}/timetrack"
            params: Dict[str, Any] = {
                "dateFrom": date_from,
                "dateTo": date_to,
            }

            # Optional filters
            if table_options.get("userIds"):
                params["userIds"] = table_options["userIds"]
            if table_options.get("taskIds"):
                params["taskIds"] = table_options["taskIds"]

            response = self._make_request_with_retry("GET", url, params=params)

            if response.status_code != 200:
                raise ActitimeAPIError.from_response(response, url)

            data = response.json()

            # Handle timetrack response structure
            # Response format: {"dateFrom": "...", "dateTo": "...", "data": [...]}
            if isinstance(data, dict) and "data" in data:
                items = data.get("data", [])
            elif isinstance(data, dict) and "items" in data:
                items = data.get("items", [])
            elif isinstance(data, list):
                items = data
            else:
                items = []

            # Flatten nested structure - each item has userId, date, and records array
            records: List[Dict[str, Any]] = []
            max_date = start_offset.get("cursor") if start_offset else None

            for user_entry in items:
                # Handle the actual structure from the API
                user_id = user_entry.get("userId")
                date = user_entry.get("date")

                # Get records array, if exists
                entry_records = user_entry.get("records", [])
                if entry_records:
                    for record in entry_records:
                        flattened = {
                            "id": record.get("id"),
                            "userId": user_id,
                            "date": date,
                            "taskId": record.get("taskId"),
                            "time": record.get("time"),
                            "comment": record.get("comment"),
                            "approved": record.get("approved"),
                            "locked": record.get("locked"),
                            "typeOfWorkId": record.get("typeOfWorkId"),
                        }
                        records.append(flattened)
                else:
                    # No nested records - might be flat structure
                    # Try to use the entry directly if it has required fields
                    if user_entry.get("id") is not None or user_entry.get("taskId") is not None:
                        flattened = {
                            "id": user_entry.get("id"),
                            "userId": user_id,
                            "date": date,
                            "taskId": user_entry.get("taskId"),
                            "time": user_entry.get("time"),
                            "comment": user_entry.get("comment"),
                            "approved": user_entry.get("approved"),
                            "locked": user_entry.get("locked"),
                            "typeOfWorkId": user_entry.get("typeOfWorkId"),
                        }
                        records.append(flattened)

                if date and (max_date is None or date > max_date):
                    max_date = date

            next_offset = {"cursor": max_date} if max_date else {}
            return iter(records), next_offset

        def _read_leavetime(
            self,
            start_offset: Dict[str, Any],
            table_options: Dict[str, str],
        ) -> Tuple[Iterator[Dict[str, Any]], Dict[str, Any]]:
            """
            Read leavetime entries with date range filtering.

            Optional table_options:
                - dateFrom: Start date (YYYY-MM-DD). Defaults to offset cursor or 90 days ago
                - dateTo: End date (YYYY-MM-DD). Defaults to today
            """
            # Smart defaults for date range
            date_from = table_options.get("dateFrom")
            date_to = table_options.get("dateTo")

            # If not provided, use intelligent defaults
            if not date_from:
                # Use cursor from offset if available, otherwise go back 90 days
                if start_offset and "cursor" in start_offset:
                    date_from = start_offset["cursor"]
                else:
                    date_from = (datetime.now() - timedelta(days=90)).strftime("%Y-%m-%d")

            if not date_to:
                # Default to today
                date_to = datetime.now().strftime("%Y-%m-%d")

            url = f"{self.base_url}/leavetime"
            params: Dict[str, Any] = {
                "dateFrom": date_from,
                "dateTo": date_to,
            }

            # Optional filters
            if table_options.get("userIds"):
                params["userIds"] = table_options["userIds"]
            if table_options.get("leaveTypeIds"):
                params["leaveTypeIds"] = table_options["leaveTypeIds"]

            response = self._make_request_with_retry("GET", url, params=params)

            if response.status_code != 200:
                raise ActitimeAPIError.from_response(response, url)

            data = response.json()

            # Handle leavetime response structure
            # Response format: {"dateFrom": "...", "dateTo": "...", "data": [...]}
            if isinstance(data, dict) and "data" in data:
                items = data.get("data", [])
            elif isinstance(data, dict) and "items" in data:
                items = data.get("items", [])
            elif isinstance(data, list):
                items = data
            else:
                items = []

            # Flatten nested structure - each item has userId, date, and records array
            records: List[Dict[str, Any]] = []
            max_date = start_offset.get("cursor") if start_offset else None

            for user_entry in items:
                # Handle the actual structure from the API
                user_id = user_entry.get("userId")
                date = user_entry.get("date")

                # Get records array, if exists
                entry_records = user_entry.get("records", [])
                if entry_records:
                    for record in entry_records:
                        flattened = {
                            "id": record.get("id"),
                            "userId": user_id,
                            "date": date,
                            "leaveTypeId": record.get("leaveTypeId"),
                            "time": record.get("time"),
                            "approved": record.get("approved"),
                        }
                        records.append(flattened)
                else:
                    # No nested records - might be flat structure
                    if user_entry.get("id") is not None or user_entry.get("leaveTypeId") is not None:
                        flattened = {
                            "id": user_entry.get("id"),
                            "userId": user_id,
                            "date": date,
                            "leaveTypeId": user_entry.get("leaveTypeId"),
                            "time": user_entry.get("time"),
                            "approved": user_entry.get("approved"),
                        }
                        records.append(flattened)

                if date and (max_date is None or date > max_date):
                    max_date = date

            next_offset = {"cursor": max_date} if max_date else {}
            return iter(records), next_offset

        # =========================================================================
        # Reader Methods - Simple Endpoints (Snapshot)
        # =========================================================================

        def _read_simple(
            self,
            endpoint: str,
            allow_not_found: bool = False,
        ) -> Tuple[Iterator[Dict[str, Any]], Dict[str, Any]]:
            """
            Generic reader for simple endpoints without pagination.

            Args:
                endpoint: API endpoint name
                allow_not_found: If True, return empty results for 404 (endpoint may not exist)

            Returns:
                Tuple of (records iterator, empty offset)
            """
            url = f"{self.base_url}/{endpoint}"
            response = self._make_request_with_retry("GET", url)

            if response.status_code == 404 and allow_not_found:
                # Endpoint doesn't exist in this actiTIME instance
                return iter([]), {}

            if response.status_code != 200:
                raise ActitimeAPIError.from_response(response, url)

            data = response.json()

            # Handle paginated response structure with 'items' key
            if isinstance(data, dict) and "items" in data:
                return iter(data.get("items", [])), {}
            elif isinstance(data, list):
                return iter(data), {}
            else:
                # Singleton response (e.g., settings)
                return iter([data]), {}

        def _read_departments(
            self,
            start_offset: Dict[str, Any],
            table_options: Dict[str, str],
        ) -> Tuple[Iterator[Dict[str, Any]], Dict[str, Any]]:
            """Read departments (snapshot)."""
            return self._read_simple("departments")

        def _read_types_of_work(
            self,
            start_offset: Dict[str, Any],
            table_options: Dict[str, str],
        ) -> Tuple[Iterator[Dict[str, Any]], Dict[str, Any]]:
            """Read types of work (snapshot)."""
            return self._read_simple("typesOfWork")

        def _read_leave_types(
            self,
            start_offset: Dict[str, Any],
            table_options: Dict[str, str],
        ) -> Tuple[Iterator[Dict[str, Any]], Dict[str, Any]]:
            """Read leave types (snapshot)."""
            return self._read_simple("leaveTypes")

        def _read_workflow_statuses(
            self,
            start_offset: Dict[str, Any],
            table_options: Dict[str, str],
        ) -> Tuple[Iterator[Dict[str, Any]], Dict[str, Any]]:
            """Read workflow statuses (snapshot)."""
            return self._read_simple("workflowStatuses")

        def _read_time_zone_groups(
            self,
            start_offset: Dict[str, Any],
            table_options: Dict[str, str],
        ) -> Tuple[Iterator[Dict[str, Any]], Dict[str, Any]]:
            """Read time zone groups (snapshot)."""
            return self._read_simple("timeZoneGroups")

        def _read_info(
            self,
            start_offset: Dict[str, Any],
            table_options: Dict[str, str],
        ) -> Tuple[Iterator[Dict[str, Any]], Dict[str, Any]]:
            """
            Read system info (singleton snapshot).

            The /info endpoint returns system settings including company info,
            format settings, enabled features, URLs, and limits.
            """
            records_iter, next_offset = self._read_simple("info")

            def add_synthetic_id(records: Iterator[Dict[str, Any]]) -> Iterator[Dict[str, Any]]:
                """Add synthetic id to each record for primary key requirement."""
                for record in records:
                    record["id"] = "system"
                    yield record

            return add_synthetic_id(records_iter), next_offset

        # =========================================================================
        # Reader Methods - Parent-Child Pattern
        # =========================================================================

        def _read_user_rates(
            self,
            start_offset: Dict[str, Any],
            table_options: Dict[str, str],
        ) -> Tuple[Iterator[Dict[str, Any]], Dict[str, Any]]:
            """
            Read user rates (parent-child pattern).

            This requires fetching all users first, then fetching rates for each user.
            """
            # First, get all users
            users_iter, _ = self._read_users({}, table_options)
            users = list(users_iter)

            records: List[Dict[str, Any]] = []

            for user in users:
                user_id = user.get("id")
                if not user_id:
                    continue

                url = f"{self.base_url}/userRates/{user_id}"
                response = self._make_request_with_retry("GET", url)

                if response.status_code == 404:
                    # User has no rates, skip
                    continue

                if response.status_code != 200:
                    raise ActitimeAPIError.from_response(response, url)

                rates_data = response.json()

                # Handle both list and single object responses
                if isinstance(rates_data, dict):
                    rates_data = [rates_data]

                for rate in rates_data:
                    record = {
                        "userId": user_id,
                        "dateFrom": rate.get("dateFrom"),
                        "regularRate": rate.get("regularRate"),
                        "overtimeRate": rate.get("overtimeRate"),
                        "leaveRates": rate.get("leaveRates"),
                    }
                    records.append(record)

            return iter(records), {}


    ########################################################
    # pipeline/lakeflow_python_source.py
    ########################################################

    METADATA_TABLE = "_lakeflow_metadata"
    TABLE_NAME = "tableName"
    TABLE_NAME_LIST = "tableNameList"
    TABLE_CONFIGS = "tableConfigs"
    IS_DELETE_FLOW = "isDeleteFlow"


    class LakeflowStreamReader(SimpleDataSourceStreamReader):
        """
        Implements a data source stream reader for Lakeflow Connect.
        Currently, only the simpleStreamReader is implemented, which uses a
        more generic protocol suitable for most data sources that support
        incremental loading.
        """

        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.lakeflow_connect = lakeflow_connect
            self.schema = schema

        def initialOffset(self):
            return {}

        def read(self, start: dict) -> (Iterator[tuple], dict):
            is_delete_flow = self.options.get(IS_DELETE_FLOW) == "true"
            # Strip delete flow options before passing to connector
            table_options = {
                k: v for k, v in self.options.items() if k != IS_DELETE_FLOW
            }

            if is_delete_flow:
                records, offset = self.lakeflow_connect.read_table_deletes(
                    self.options[TABLE_NAME], start, table_options
                )
            else:
                records, offset = self.lakeflow_connect.read_table(
                    self.options[TABLE_NAME], start, table_options
                )
            rows = map(lambda x: parse_value(x, self.schema), records)
            return rows, offset

        def readBetweenOffsets(self, start: dict, end: dict) -> Iterator[tuple]:
            # TODO: This does not ensure the records returned are identical across repeated calls.
            # For append-only tables, the data source must guarantee that reading from the same
            # start offset will always yield the same set of records.
            # For tables ingested as incremental CDC, it is only necessary that no new changes
            # are missed in the returned records.
            return self.read(start)[0]


    class LakeflowBatchReader(DataSourceReader):
        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.schema = schema
            self.lakeflow_connect = lakeflow_connect
            self.table_name = options[TABLE_NAME]

        def read(self, partition):
            all_records = []
            if self.table_name == METADATA_TABLE:
                all_records = self._read_table_metadata()
            else:
                all_records, _ = self.lakeflow_connect.read_table(
                    self.table_name, None, self.options
                )

            rows = map(lambda x: parse_value(x, self.schema), all_records)
            return iter(rows)

        def _read_table_metadata(self):
            table_name_list = self.options.get(TABLE_NAME_LIST, "")
            table_names = [o.strip() for o in table_name_list.split(",") if o.strip()]
            all_records = []
            table_configs = json.loads(self.options.get(TABLE_CONFIGS, "{}"))
            for table in table_names:
                metadata = self.lakeflow_connect.read_table_metadata(
                    table, table_configs.get(table, {})
                )
                all_records.append({TABLE_NAME: table, **metadata})
            return all_records


    class LakeflowSource(DataSource):
        def __init__(self, options):
            self.options = options
            self.lakeflow_connect = LakeflowConnect(options)

        @classmethod
        def name(cls):
            return "lakeflow_connect"

        def schema(self):
            table = self.options[TABLE_NAME]
            if table == METADATA_TABLE:
                return StructType(
                    [
                        StructField(TABLE_NAME, StringType(), False),
                        StructField("primary_keys", ArrayType(StringType()), True),
                        StructField("cursor_field", StringType(), True),
                        StructField("ingestion_type", StringType(), True),
                    ]
                )
            else:
                # Assuming the LakeflowConnect interface uses get_table_schema, not get_table_details
                return self.lakeflow_connect.get_table_schema(table, self.options)

        def reader(self, schema: StructType):
            return LakeflowBatchReader(self.options, schema, self.lakeflow_connect)

        def simpleStreamReader(self, schema: StructType):
            return LakeflowStreamReader(self.options, schema, self.lakeflow_connect)


    spark.dataSource.register(LakeflowSource)  # pylint: disable=undefined-variable
