# ==============================================================================
# Merged Lakeflow Source: open_meteo
# ==============================================================================
# This file is auto-generated by tools/scripts/merge_python_source.py
# Do not edit manually. Make changes to the source files instead.
# ==============================================================================

from datetime import datetime, timedelta
from decimal import Decimal
from typing import (
    Any,
    Dict,
    Iterator,
    List,
    Tuple,
)
import json
import time

from pyspark.sql import Row
from pyspark.sql.datasource import DataSource, DataSourceReader, SimpleDataSourceStreamReader
from pyspark.sql.types import *
import base64
import requests


def register_lakeflow_source(spark):
    """Register the Lakeflow Python source with Spark."""

    ########################################################
    # libs/utils.py
    ########################################################

    def _parse_struct(value: Any, field_type: StructType) -> Row:
        """Parse a dictionary into a PySpark Row based on StructType schema."""
        if not isinstance(value, dict):
            raise ValueError(f"Expected a dictionary for StructType, got {type(value)}")
        # Spark Python -> Arrow conversion require missing StructType fields to be assigned None.
        if value == {}:
            raise ValueError(
                "field in StructType cannot be an empty dict. "
                "Please assign None as the default value instead."
            )
        field_dict = {}
        for field in field_type.fields:
            if field.name in value:
                field_dict[field.name] = parse_value(value.get(field.name), field.dataType)
            elif field.nullable:
                field_dict[field.name] = None
            else:
                raise ValueError(f"Field {field.name} is not nullable but not found in the input")
        return Row(**field_dict)


    def _parse_array(value: Any, field_type: ArrayType) -> list:
        """Parse a list into a PySpark array based on ArrayType schema."""
        if not isinstance(value, list):
            if field_type.containsNull:
                return [parse_value(value, field_type.elementType)]
            raise ValueError(f"Expected a list for ArrayType, got {type(value)}")
        return [parse_value(v, field_type.elementType) for v in value]


    def _parse_map(value: Any, field_type: MapType) -> dict:
        """Parse a dictionary into a PySpark map based on MapType schema."""
        if not isinstance(value, dict):
            raise ValueError(f"Expected a dictionary for MapType, got {type(value)}")
        return {
            parse_value(k, field_type.keyType): parse_value(v, field_type.valueType)
            for k, v in value.items()
        }


    def _parse_string(value: Any) -> str:
        """Convert value to string."""
        return str(value)


    def _parse_integer(value: Any) -> int:
        """Convert value to integer."""
        if isinstance(value, str) and value.strip():
            return int(float(value)) if "." in value else int(value)
        if isinstance(value, (int, float)):
            return int(value)
        raise ValueError(f"Cannot convert {value} to integer")


    def _parse_float(value: Any) -> float:
        """Convert value to float."""
        return float(value)


    def _parse_decimal(value: Any) -> Decimal:
        """Convert value to Decimal."""
        return Decimal(value) if isinstance(value, str) and value.strip() else Decimal(str(value))


    def _parse_boolean(value: Any) -> bool:
        """Convert value to boolean."""
        if isinstance(value, str):
            lowered = value.lower()
            if lowered in ("true", "t", "yes", "y", "1"):
                return True
            if lowered in ("false", "f", "no", "n", "0"):
                return False
        return bool(value)


    def _parse_date(value: Any) -> datetime.date:
        """Convert value to date."""
        if isinstance(value, str):
            for fmt in ("%Y-%m-%d", "%m/%d/%Y", "%d-%m-%Y", "%Y/%m/%d"):
                try:
                    return datetime.strptime(value, fmt).date()
                except ValueError:
                    continue
            return datetime.fromisoformat(value).date()
        if isinstance(value, datetime):
            return value.date()
        raise ValueError(f"Cannot convert {value} to date")


    def _parse_timestamp(value: Any) -> datetime:
        """Convert value to timestamp."""
        if isinstance(value, str):
            ts_value = value.replace("Z", "+00:00") if value.endswith("Z") else value
            try:
                return datetime.fromisoformat(ts_value)
            except ValueError:
                for fmt in ("%Y-%m-%d %H:%M:%S", "%Y/%m/%d %H:%M:%S"):
                    try:
                        return datetime.strptime(ts_value, fmt)
                    except ValueError:
                        continue
        elif isinstance(value, (int, float)):
            return datetime.fromtimestamp(value)
        elif isinstance(value, datetime):
            return value
        raise ValueError(f"Cannot convert {value} to timestamp")


    def _decode_string_to_bytes(value: str) -> bytes:
        """Try to decode a string as base64, then hex, then UTF-8."""
        try:
            return base64.b64decode(value)
        except Exception:
            pass
        try:
            return bytes.fromhex(value)
        except Exception:
            pass
        return value.encode("utf-8")


    def _parse_binary(value: Any) -> bytes:
        """Convert value to bytes. Tries base64, then hex, then UTF-8 for strings."""
        if isinstance(value, bytes):
            return value
        if isinstance(value, bytearray):
            return bytes(value)
        if isinstance(value, str):
            return _decode_string_to_bytes(value)
        if isinstance(value, list):
            return bytes(value)
        return str(value).encode("utf-8")


    # Mapping of primitive types to their parser functions
    _PRIMITIVE_PARSERS = {
        StringType: _parse_string,
        IntegerType: _parse_integer,
        LongType: _parse_integer,
        FloatType: _parse_float,
        DoubleType: _parse_float,
        DecimalType: _parse_decimal,
        BooleanType: _parse_boolean,
        DateType: _parse_date,
        TimestampType: _parse_timestamp,
        BinaryType: _parse_binary,
    }


    def parse_value(value: Any, field_type: DataType) -> Any:
        """
        Converts a JSON value into a PySpark-compatible data type based on the provided field type.
        """
        if value is None:
            return None

        # Handle complex types
        if isinstance(field_type, StructType):
            return _parse_struct(value, field_type)
        if isinstance(field_type, ArrayType):
            return _parse_array(value, field_type)
        if isinstance(field_type, MapType):
            return _parse_map(value, field_type)

        # Handle primitive types via type-based lookup
        try:
            field_type_class = type(field_type)
            if field_type_class in _PRIMITIVE_PARSERS:
                return _PRIMITIVE_PARSERS[field_type_class](value)

            # Check for custom UDT handling
            if hasattr(field_type, "fromJson"):
                return field_type.fromJson(value)

            raise TypeError(f"Unsupported field type: {field_type}")
        except (ValueError, TypeError) as e:
            raise ValueError(f"Error converting '{value}' ({type(value)}) to {field_type}: {str(e)}")


    ########################################################
    # sources/open_meteo/open_meteo.py
    ########################################################

    class LakeflowConnect:  # pylint: disable=too-many-instance-attributes
        """
        Open-Meteo connector for Lakeflow Community Connectors.

        Provides access to weather forecasts, historical weather data, air quality,
        and marine weather via the Open-Meteo API.

        Multi-Location Support:
            The connector supports comma-separated latitude/longitude pairs
            (e.g., "52.52,48.85" for latitudes). The API will return data for
            each location in a single request, which is more efficient than
            multiple API calls.
        """

        # Rate limit configurations by tier
        RATE_LIMIT_TIERS = {
            "free": {
                "per_minute": 600,
                "per_hour": 5000,
                "per_day": 10000,
                "per_month": 300000
            },
            "standard": {
                "per_minute": None,  # Unlimited
                "per_hour": None,
                "per_day": None,
                "per_month": 1000000
            },
            "professional": {
                "per_minute": None,
                "per_hour": None,
                "per_day": None,
                "per_month": 5000000
            },
            "enterprise": {
                "per_minute": None,
                "per_hour": None,
                "per_day": None,
                "per_month": 50000000
            },
        }

        def __init__(self, options: Dict[str, str]) -> None:
            """
            Initialize the Open-Meteo connector.

            Args:
                options: Dictionary with the following keys:
                    - api_key (optional): API key for commercial tier. If not provided, uses free tier.
                    - latitude (optional): Default latitude for weather queries
                          (can be overridden in table_options)
                    - longitude (optional): Default longitude for weather queries
                          (can be overridden in table_options)
                    - tier (optional): Rate limit tier - one of: "free",
                          "standard", "professional", "enterprise"
                          (default: "free" if no api_key, "standard" if api_key)
                    - requests_per_minute (optional): Override requests per minute limit
                    - requests_per_day (optional): Override daily request limit
                    - timeout (optional): Request timeout in seconds (default: 30)
            """
            self.api_key = options.get("api_key")
            self.default_latitude = options.get("latitude")
            self.default_longitude = options.get("longitude")

            # Determine if using commercial or free tier
            self.is_commercial = self.api_key is not None

            # Configure rate limiting based on tier
            if self.is_commercial:
                default_tier = "standard"
            else:
                default_tier = "free"

            tier = options.get("tier", default_tier).lower()
            if tier not in self.RATE_LIMIT_TIERS:
                raise ValueError(
                    f"Invalid tier: {tier}. Valid tiers are: {list(self.RATE_LIMIT_TIERS.keys())}"
                )

            tier_config = self.RATE_LIMIT_TIERS[tier]

            # Allow explicit overrides
            self.requests_per_minute = tier_config.get("per_minute")
            if "requests_per_minute" in options:
                try:
                    self.requests_per_minute = int(options["requests_per_minute"])
                except (TypeError, ValueError):
                    pass

            self.requests_per_day = tier_config.get("per_day")
            if "requests_per_day" in options:
                try:
                    self.requests_per_day = int(options["requests_per_day"])
                except (TypeError, ValueError):
                    pass

            # Rate limiting state
            self._request_timestamps: List[float] = []
            self._daily_request_count = 0
            self._daily_reset_time = time.time()

            # Request timeout
            self.timeout = int(options.get("timeout", 30))

            # Configure HTTP session for connection reuse
            self._session = requests.Session()
            self._session.headers.update({
                "User-Agent": "LakeflowConnect-OpenMeteo/1.0",
                "Accept": "application/json"
            })

            # Schema cache
            self._schema_cache = {}

            # Set base URLs based on tier
            if self.is_commercial:
                self.forecast_base_url = "https://customer-api.open-meteo.com/v1"
                self.archive_base_url = "https://customer-archive-api.open-meteo.com/v1"
                self.air_quality_base_url = "https://customer-air-quality-api.open-meteo.com/v1"
                self.marine_base_url = "https://customer-marine-api.open-meteo.com/v1"
                self.geocoding_base_url = "https://customer-geocoding-api.open-meteo.com/v1"
            else:
                self.forecast_base_url = "https://api.open-meteo.com/v1"
                self.archive_base_url = "https://archive-api.open-meteo.com/v1"
                self.air_quality_base_url = "https://air-quality-api.open-meteo.com/v1"
                self.marine_base_url = "https://marine-api.open-meteo.com/v1"
                self.geocoding_base_url = "https://geocoding-api.open-meteo.com/v1"

            # Initialize centralized table configuration
            self._init_table_config()

        def _init_table_config(self) -> None:
            """Initialize centralized table configuration."""
            self._table_config = {
                "weather_forecast_hourly": {
                    "primary_keys": ["latitude", "longitude", "time"],
                    "cursor_field": "time",
                    "ingestion_type": "append",
                    "endpoint": "forecast",
                    "data_key": "hourly",
                    "forecast_days": 16,
                    "default_variables": (
                        "temperature_2m,relative_humidity_2m,precipitation,rain,snowfall,"
                        "weather_code,pressure_msl,cloud_cover,wind_speed_10m,wind_direction_10m"
                    ),
                },
                "weather_forecast_daily": {
                    "primary_keys": ["latitude", "longitude", "time"],
                    "cursor_field": "time",
                    "ingestion_type": "append",
                    "endpoint": "forecast",
                    "data_key": "daily",
                    "forecast_days": 16,
                    "default_variables": (
                        "weather_code,temperature_2m_max,temperature_2m_min,precipitation_sum,"
                        "rain_sum,snowfall_sum,wind_speed_10m_max,wind_direction_10m_dominant"
                    ),
                },
                "historical_weather_hourly": {
                    "primary_keys": ["latitude", "longitude", "time"],
                    "ingestion_type": "snapshot",
                    "endpoint": "archive",
                    "data_key": "hourly",
                    "default_variables": (
                        "temperature_2m,relative_humidity_2m,precipitation,rain,snowfall,"
                        "weather_code,pressure_msl,cloud_cover,wind_speed_10m,wind_direction_10m"
                    ),
                },
                "historical_weather_daily": {
                    "primary_keys": ["latitude", "longitude", "time"],
                    "ingestion_type": "snapshot",
                    "endpoint": "archive",
                    "data_key": "daily",
                    "default_variables": (
                        "weather_code,temperature_2m_max,temperature_2m_min,precipitation_sum,"
                        "rain_sum,snowfall_sum,wind_speed_10m_max,wind_direction_10m_dominant"
                    ),
                },
                "air_quality_hourly": {
                    "primary_keys": ["latitude", "longitude", "time"],
                    "cursor_field": "time",
                    "ingestion_type": "append",
                    "endpoint": "air-quality",
                    "data_key": "hourly",
                    "forecast_days": 7,
                    "default_variables": (
                        "pm10,pm2_5,carbon_monoxide,nitrogen_dioxide,sulphur_dioxide,"
                        "ozone,european_aqi,us_aqi"
                    ),
                },
                "marine_weather_hourly": {
                    "primary_keys": ["latitude", "longitude", "time"],
                    "cursor_field": "time",
                    "ingestion_type": "append",
                    "endpoint": "marine",
                    "data_key": "hourly",
                    "forecast_days": 8,
                    "default_variables": (
                        "wave_height,wave_direction,wave_period,sea_surface_temperature,"
                        "ocean_current_velocity,ocean_current_direction"
                    ),
                },
                "marine_weather_daily": {
                    "primary_keys": ["latitude", "longitude", "time"],
                    "cursor_field": "time",
                    "ingestion_type": "append",
                    "endpoint": "marine",
                    "data_key": "daily",
                    "forecast_days": 8,
                    "default_variables": "wave_height_max,wave_direction_dominant,wave_period_max",
                },
                "geocoding": {
                    "primary_keys": ["id"],
                    "ingestion_type": "snapshot",
                    "endpoint": "search",
                    "api_base": "geocoding",
                    "default_count": 10,
                },
            }

        def _enforce_rate_limit(self) -> None:
            """Enforce rate limiting based on configured tier."""
            current_time = time.time()

            # Reset daily counter if needed (24 hours)
            if current_time - self._daily_reset_time >= 86400:
                self._daily_request_count = 0
                self._daily_reset_time = current_time

            # Check daily limit
            if self.requests_per_day is not None:
                if self._daily_request_count >= self.requests_per_day:
                    raise RuntimeError(
                        f"Daily rate limit exceeded ({self.requests_per_day} requests/day)"
                    )

            # Check per-minute limit using sliding window
            if self.requests_per_minute is not None:
                # Remove timestamps older than 60 seconds
                self._request_timestamps = [
                    ts for ts in self._request_timestamps if current_time - ts < 60
                ]

                if len(self._request_timestamps) >= self.requests_per_minute:
                    # Calculate sleep time until oldest request expires
                    sleep_time = 60 - (current_time - self._request_timestamps[0]) + 0.1
                    if sleep_time > 0:
                        time.sleep(sleep_time)
                    self._request_timestamps = []

            # Record this request
            self._request_timestamps.append(current_time)
            self._daily_request_count += 1

        def _make_request(
            self, url: str, params: Dict[str, Any], max_retries: int = 3
        ) -> Dict[str, Any]:
            """
            Make an API request with retry logic and error handling.

            Args:
                url: API endpoint URL
                params: Query parameters
                max_retries: Maximum number of retry attempts

            Returns:
                JSON response as dictionary

            Raises:
                requests.exceptions.RequestException: On request failure after retries
            """
            for attempt in range(max_retries):
                try:
                    # Enforce rate limiting
                    self._enforce_rate_limit()

                    # Make request
                    response = self._session.get(url, params=params, timeout=self.timeout)

                    # Handle rate limiting response
                    if response.status_code == 429:
                        retry_after = int(response.headers.get("Retry-After", 60))
                        time.sleep(retry_after)
                        continue

                    # Raise for other error status codes
                    response.raise_for_status()

                    return response.json()

                except requests.exceptions.Timeout:
                    if attempt == max_retries - 1:
                        raise
                    # Exponential backoff
                    time.sleep(2 ** attempt)

                except requests.exceptions.RequestException as e:
                    if attempt == max_retries - 1:
                        raise
                    # Exponential backoff for transient errors
                    if hasattr(e.response, "status_code") and e.response.status_code >= 500:
                        time.sleep(2 ** attempt)
                    else:
                        raise

            raise RuntimeError("Request failed after maximum retries")

        def list_tables(self) -> List[str]:
            """
            Return the list of available Open-Meteo tables.

            Returns:
                List of table names available for ingestion
            """
            tables = list(self._table_config.keys())

            # Commercial tier additional tables (placeholder for future expansion)
            if self.is_commercial:
                # These would require additional implementation
                pass

            return tables

        def _get_base_weather_fields(self) -> List[StructField]:
            """Return common base fields for weather tables."""
            return [
                StructField("latitude", DoubleType(), False),
                StructField("longitude", DoubleType(), False),
                StructField("time", StringType(), False),
            ]

        def _get_common_weather_fields(self) -> List[StructField]:
            """Return common weather variable fields."""
            return [
                StructField("temperature_2m", DoubleType(), True),
                StructField("relative_humidity_2m", LongType(), True),
                StructField("dew_point_2m", DoubleType(), True),
                StructField("apparent_temperature", DoubleType(), True),
                StructField("precipitation", DoubleType(), True),
                StructField("rain", DoubleType(), True),
                StructField("snowfall", DoubleType(), True),
                StructField("snow_depth", DoubleType(), True),
                StructField("weather_code", LongType(), True),
                StructField("pressure_msl", DoubleType(), True),
                StructField("surface_pressure", DoubleType(), True),
                StructField("cloud_cover", LongType(), True),
                StructField("cloud_cover_low", LongType(), True),
                StructField("cloud_cover_mid", LongType(), True),
                StructField("cloud_cover_high", LongType(), True),
                StructField("visibility", DoubleType(), True),
                StructField("evapotranspiration", DoubleType(), True),
                StructField("et0_fao_evapotranspiration", DoubleType(), True),
                StructField("vapour_pressure_deficit", DoubleType(), True),
            ]

        def _get_wind_fields(self) -> List[StructField]:
            """Return wind-related fields."""
            return [
                StructField("wind_speed_10m", DoubleType(), True),
                StructField("wind_speed_80m", DoubleType(), True),
                StructField("wind_speed_120m", DoubleType(), True),
                StructField("wind_direction_10m", LongType(), True),
                StructField("wind_direction_80m", LongType(), True),
                StructField("wind_direction_120m", LongType(), True),
                StructField("wind_gusts_10m", DoubleType(), True),
            ]

        def _get_radiation_fields(self) -> List[StructField]:
            """Return solar radiation fields."""
            return [
                StructField("shortwave_radiation", DoubleType(), True),
                StructField("direct_radiation", DoubleType(), True),
                StructField("diffuse_radiation", DoubleType(), True),
                StructField("direct_normal_irradiance", DoubleType(), True),
                StructField("global_tilted_irradiance", DoubleType(), True),
                StructField("terrestrial_radiation", DoubleType(), True),
                StructField("shortwave_radiation_instant", DoubleType(), True),
                StructField("diffuse_radiation_instant", DoubleType(), True),
                StructField("direct_normal_irradiance_instant", DoubleType(), True),
            ]

        def _get_soil_fields(self) -> List[StructField]:
            """Return soil-related fields."""
            return [
                StructField("soil_temperature_0cm", DoubleType(), True),
                StructField("soil_temperature_6cm", DoubleType(), True),
                StructField("soil_temperature_18cm", DoubleType(), True),
                StructField("soil_temperature_54cm", DoubleType(), True),
                StructField("soil_moisture_0_to_1cm", DoubleType(), True),
                StructField("soil_moisture_1_to_3cm", DoubleType(), True),
                StructField("soil_moisture_3_to_9cm", DoubleType(), True),
                StructField("soil_moisture_9_to_27cm", DoubleType(), True),
                StructField("soil_moisture_27_to_81cm", DoubleType(), True),
            ]

        def _get_hourly_weather_schema(self) -> StructType:
            """Return schema for hourly weather forecast/historical tables."""
            fields = self._get_base_weather_fields()
            fields.extend(self._get_common_weather_fields())
            fields.extend(self._get_wind_fields())
            fields.extend(self._get_radiation_fields())
            fields.extend(self._get_soil_fields())
            return StructType(fields)

        def _get_daily_weather_schema(self) -> StructType:
            """Return schema for daily weather forecast/historical tables."""
            fields = self._get_base_weather_fields()
            fields.extend([
                StructField("weather_code", LongType(), True),
                StructField("temperature_2m_max", DoubleType(), True),
                StructField("temperature_2m_min", DoubleType(), True),
                StructField("apparent_temperature_max", DoubleType(), True),
                StructField("apparent_temperature_min", DoubleType(), True),
                StructField("sunrise", StringType(), True),
                StructField("sunset", StringType(), True),
                StructField("daylight_duration", DoubleType(), True),
                StructField("sunshine_duration", DoubleType(), True),
                StructField("uv_index_max", DoubleType(), True),
                StructField("uv_index_clear_sky_max", DoubleType(), True),
                StructField("precipitation_sum", DoubleType(), True),
                StructField("rain_sum", DoubleType(), True),
                StructField("snowfall_sum", DoubleType(), True),
                StructField("precipitation_hours", LongType(), True),
                StructField("precipitation_probability_max", LongType(), True),
                StructField("wind_speed_10m_max", DoubleType(), True),
                StructField("wind_gusts_10m_max", DoubleType(), True),
                StructField("wind_direction_10m_dominant", LongType(), True),
                StructField("shortwave_radiation_sum", DoubleType(), True),
                StructField("et0_fao_evapotranspiration", DoubleType(), True),
            ])
            return StructType(fields)

        def _get_air_quality_schema(self) -> StructType:
            """Return schema for air quality table."""
            fields = self._get_base_weather_fields()
            fields.extend([
                StructField("pm10", DoubleType(), True),
                StructField("pm2_5", DoubleType(), True),
                StructField("carbon_monoxide", DoubleType(), True),
                StructField("nitrogen_dioxide", DoubleType(), True),
                StructField("sulphur_dioxide", DoubleType(), True),
                StructField("ozone", DoubleType(), True),
                StructField("carbon_dioxide", DoubleType(), True),
                StructField("ammonia", DoubleType(), True),
                StructField("aerosol_optical_depth", DoubleType(), True),
                StructField("dust", DoubleType(), True),
                StructField("uv_index", DoubleType(), True),
                StructField("uv_index_clear_sky", DoubleType(), True),
                StructField("alder_pollen", LongType(), True),
                StructField("birch_pollen", LongType(), True),
                StructField("grass_pollen", LongType(), True),
                StructField("mugwort_pollen", LongType(), True),
                StructField("olive_pollen", LongType(), True),
                StructField("ragweed_pollen", LongType(), True),
                StructField("european_aqi", LongType(), True),
                StructField("european_aqi_pm2_5", LongType(), True),
                StructField("european_aqi_pm10", LongType(), True),
                StructField("european_aqi_no2", LongType(), True),
                StructField("european_aqi_o3", LongType(), True),
                StructField("european_aqi_so2", LongType(), True),
                StructField("us_aqi", LongType(), True),
                StructField("us_aqi_pm2_5", LongType(), True),
                StructField("us_aqi_pm10", LongType(), True),
                StructField("us_aqi_no2", LongType(), True),
                StructField("us_aqi_co", LongType(), True),
                StructField("us_aqi_o3", LongType(), True),
                StructField("us_aqi_so2", LongType(), True),
            ])
            return StructType(fields)

        def _get_marine_hourly_schema(self) -> StructType:
            """Return schema for hourly marine weather table."""
            fields = self._get_base_weather_fields()
            fields.extend([
                StructField("wave_height", DoubleType(), True),
                StructField("wave_direction", LongType(), True),
                StructField("wave_period", DoubleType(), True),
                StructField("wind_wave_height", DoubleType(), True),
                StructField("wind_wave_direction", LongType(), True),
                StructField("wind_wave_period", DoubleType(), True),
                StructField("wind_wave_peak_period", DoubleType(), True),
                StructField("swell_wave_height", DoubleType(), True),
                StructField("swell_wave_direction", LongType(), True),
                StructField("swell_wave_period", DoubleType(), True),
                StructField("swell_wave_peak_period", DoubleType(), True),
                StructField("ocean_current_velocity", DoubleType(), True),
                StructField("ocean_current_direction", LongType(), True),
                StructField("sea_surface_temperature", DoubleType(), True),
            ])
            return StructType(fields)

        def _get_marine_daily_schema(self) -> StructType:
            """Return schema for daily marine weather table."""
            fields = self._get_base_weather_fields()
            fields.extend([
                StructField("wave_height_max", DoubleType(), True),
                StructField("wave_direction_dominant", LongType(), True),
                StructField("wave_period_max", DoubleType(), True),
                StructField("wind_wave_height_max", DoubleType(), True),
                StructField("swell_wave_height_max", DoubleType(), True),
            ])
            return StructType(fields)

        def _get_geocoding_schema(self) -> StructType:
            """
            Return the schema for geocoding search results.

            Geocoding allows searching for locations by name and returns
            coordinates, administrative boundaries, and location metadata.
            """
            return StructType([
                # Primary key
                StructField("id", LongType(), False),
                # Location identification
                StructField("name", StringType(), False),
                StructField("latitude", DoubleType(), False),
                StructField("longitude", DoubleType(), False),
                # Additional metadata
                StructField("elevation", DoubleType(), True),
                StructField("feature_code", StringType(), True),
                StructField("country_code", StringType(), True),
                StructField("country", StringType(), True),
                # Administrative boundaries (hierarchical)
                StructField("admin1", StringType(), True),  # State/region
                StructField("admin2", StringType(), True),  # County
                StructField("admin3", StringType(), True),  # Municipality
                StructField("admin4", StringType(), True),  # District
                # Additional location info
                StructField("timezone", StringType(), True),
                StructField("population", LongType(), True),
                StructField("postcodes", ArrayType(StringType(), True), True),
            ])

        def get_table_schema(
            self, table_name: str, table_options: Dict[str, str]  # pylint: disable=unused-argument
        ) -> StructType:
            """
            Fetch the schema of a table.

            Args:
                table_name: Name of the table
                table_options: Additional options for the table

            Returns:
                StructType representing the table schema
            """
            if table_name not in self._table_config:
                raise ValueError(
                    f"Table '{table_name}' is not supported. "
                    f"Supported tables: {list(self._table_config.keys())}"
                )

            # Check cache first
            if table_name in self._schema_cache:
                return self._schema_cache[table_name]

            # Build schema based on table type
            if table_name in ["weather_forecast_hourly", "historical_weather_hourly"]:
                schema = self._get_hourly_weather_schema()
            elif table_name in ["weather_forecast_daily", "historical_weather_daily"]:
                schema = self._get_daily_weather_schema()
            elif table_name == "air_quality_hourly":
                schema = self._get_air_quality_schema()
            elif table_name == "marine_weather_hourly":
                schema = self._get_marine_hourly_schema()
            elif table_name == "marine_weather_daily":
                schema = self._get_marine_daily_schema()
            elif table_name == "geocoding":
                schema = self._get_geocoding_schema()
            else:
                raise ValueError(f"Schema not defined for table: {table_name}")

            # Cache the schema
            self._schema_cache[table_name] = schema

            return schema

        def read_table_metadata(
            self, table_name: str, table_options: Dict[str, str]  # pylint: disable=unused-argument
        ) -> dict:
            """
            Fetch the metadata of a table.

            Args:
                table_name: Name of the table
                table_options: Additional options for the table

            Returns:
                Dictionary with primary_keys, cursor_field (if applicable), and ingestion_type
            """
            if table_name not in self._table_config:
                raise ValueError(
                    f"Table '{table_name}' is not supported. "
                    f"Supported tables: {list(self._table_config.keys())}"
                )

            config = self._table_config[table_name]
            metadata = {
                "primary_keys": config["primary_keys"],
                "ingestion_type": config["ingestion_type"],
            }

            if "cursor_field" in config:
                metadata["cursor_field"] = config["cursor_field"]

            return metadata

        def read_table(
            self, table_name: str, start_offset: dict, table_options: Dict[str, str]
        ) -> Tuple[Iterator[dict], dict]:
            """
            Read data from the specified Open-Meteo table.

            Args:
                table_name: Name of the table to read
                start_offset: Dictionary containing the offset to start reading from
                             For forecast tables: {"start_date": "YYYY-MM-DD"}
                             For historical tables: requires start_date/end_date in table_options
                table_options: Additional options including:
                    - latitude (optional): Override default latitude
                          (supports comma-separated for multiple locations)
                    - longitude (optional): Override default longitude
                          (supports comma-separated for multiple locations)
                    - variables (optional): Comma-separated list of variables to fetch
                    - timezone (optional): Timezone for the data (default: GMT)
                    - start_date (required for historical tables): Start date YYYY-MM-DD
                    - end_date (required for historical tables): End date YYYY-MM-DD

            Returns:
                Tuple of (iterator of records, next offset)
            """
            if table_name not in self._table_config:
                raise ValueError(
                    f"Table '{table_name}' is not supported. "
                    f"Supported tables: {list(self._table_config.keys())}"
                )

            # Get table configuration
            config = self._table_config[table_name]

            # Handle geocoding table (doesn't require lat/lon)
            if config["endpoint"] == "search":
                return self._read_geocoding_data(config, table_options)

            # Get latitude and longitude from table_options or use defaults
            latitude = table_options.get("latitude", self.default_latitude)
            longitude = table_options.get("longitude", self.default_longitude)

            if not latitude or not longitude:
                raise ValueError(
                    "latitude and longitude must be provided either in "
                    "connection options or table_options"
                )

            # Route to appropriate read method
            if config["endpoint"] in ["forecast"]:
                return self._read_forecast_data(
                    table_name, config, start_offset, latitude, longitude, table_options
                )
            if config["endpoint"] == "archive":
                return self._read_historical_data(
                    table_name, config, latitude, longitude, table_options
                )
            if config["endpoint"] == "air-quality":
                return self._read_air_quality_data(
                    table_name, config, start_offset, latitude, longitude, table_options
                )
            if config["endpoint"] == "marine":
                return self._read_marine_data(
                    table_name, config, start_offset, latitude, longitude, table_options
                )
            raise ValueError(f"Unknown endpoint for table: {table_name}")

        def _read_forecast_data(  # pylint: disable=too-many-arguments,too-many-locals,too-many-positional-arguments,unused-argument
            self,
            table_name: str,
            config: Dict[str, Any],
            start_offset: dict,
            latitude: str,
            longitude: str,
            table_options: Dict[str, str],
        ) -> Tuple[Iterator[dict], dict]:
            """Read weather forecast data (hourly or daily)."""
            # Build API parameters using forecast_days parameter
            # Open-Meteo forecast API defaults to current date when no date params given
            params = {
                "latitude": latitude,
                "longitude": longitude,
                "forecast_days": config["forecast_days"],
                "timezone": table_options.get("timezone", "GMT"),
            }

            # Add variables
            variables = table_options.get("variables", config["default_variables"])
            params[config["data_key"]] = variables

            # Add API key if commercial
            if self.api_key:
                params["apikey"] = self.api_key

            # Make API request
            url = f"{self.forecast_base_url}/{config['endpoint']}"
            data = self._make_request(url, params)

            # Generate records
            records_iter = self._generate_records(data, config["data_key"])

            # For forecast data, return empty offset (always fetch latest forecast)
            next_offset = {}

            return records_iter, next_offset

        def _read_historical_data(  # pylint: disable=too-many-arguments,too-many-positional-arguments
            self,
            table_name: str,
            config: Dict[str, Any],
            latitude: str,
            longitude: str,
            table_options: Dict[str, str],
        ) -> Tuple[Iterator[dict], dict]:
            """Read historical weather data (hourly or daily)."""
            # For historical data, require explicit date range in table_options
            if "start_date" not in table_options or "end_date" not in table_options:
                raise ValueError(
                    f"Table '{table_name}' requires 'start_date' and 'end_date' in table_options"
                )

            start_date = table_options["start_date"]
            end_date = table_options["end_date"]

            # Build API parameters
            params = {
                "latitude": latitude,
                "longitude": longitude,
                "start_date": start_date,
                "end_date": end_date,
                "timezone": table_options.get("timezone", "GMT"),
            }

            # Add variables
            variables = table_options.get("variables", config["default_variables"])
            params[config["data_key"]] = variables

            # Add API key if commercial
            if self.api_key:
                params["apikey"] = self.api_key

            # Make API request
            url = f"{self.archive_base_url}/{config['endpoint']}"
            data = self._make_request(url, params)

            # Generate records
            records_iter = self._generate_records(data, config["data_key"])

            # For snapshot ingestion, return empty dict as offset (full refresh)
            return records_iter, {}

        def _read_air_quality_data(  # pylint: disable=too-many-arguments,too-many-locals,too-many-positional-arguments,unused-argument
            self,
            table_name: str,
            config: Dict[str, Any],
            start_offset: dict,
            latitude: str,
            longitude: str,
            table_options: Dict[str, str],
        ) -> Tuple[Iterator[dict], dict]:
            """Read air quality data."""
            # Build API parameters using forecast_days parameter
            params = {
                "latitude": latitude,
                "longitude": longitude,
                "forecast_days": config["forecast_days"],
                "timezone": table_options.get("timezone", "GMT"),
            }

            # Add variables
            variables = table_options.get("variables", config["default_variables"])
            params[config["data_key"]] = variables

            # Add API key if commercial
            if self.api_key:
                params["apikey"] = self.api_key

            # Make API request
            url = f"{self.air_quality_base_url}/{config['endpoint']}"
            data = self._make_request(url, params)

            # Generate records
            records_iter = self._generate_records(data, config["data_key"])

            # For forecast data, return empty offset (always fetch latest forecast)
            next_offset = {}

            return records_iter, next_offset

        def _read_marine_data(  # pylint: disable=too-many-arguments,too-many-locals,too-many-positional-arguments
            self,
            table_name: str,  # pylint: disable=unused-argument
            config: Dict[str, Any],
            start_offset: dict,
            latitude: str,
            longitude: str,
            table_options: Dict[str, str],
        ) -> Tuple[Iterator[dict], dict]:
            """Read marine weather data (hourly or daily)."""
            # Determine date range
            if start_offset and "start_date" in start_offset:
                start_date = start_offset["start_date"]
            else:
                start_date = datetime.now().strftime("%Y-%m-%d")

            # Calculate end date
            start_dt = datetime.strptime(start_date, "%Y-%m-%d")
            end_date = (start_dt + timedelta(days=config["forecast_days"])).strftime("%Y-%m-%d")

            # Build API parameters
            params = {
                "latitude": latitude,
                "longitude": longitude,
                "start_date": start_date,
                "end_date": end_date,
                "timezone": table_options.get("timezone", "GMT"),
            }

            # Add variables
            variables = table_options.get("variables", config["default_variables"])
            params[config["data_key"]] = variables

            # Add API key if commercial
            if self.api_key:
                params["apikey"] = self.api_key

            # Make API request
            url = f"{self.marine_base_url}/{config['endpoint']}"
            data = self._make_request(url, params)

            # Generate records
            records_iter = self._generate_records(data, config["data_key"])

            # For forecast data, return empty offset (always fetch latest forecast)
            next_offset = {}

            return records_iter, next_offset

        def _read_geocoding_data(  # pylint: disable=unused-argument
            self,
            config: Dict[str, Any],
            table_options: Dict[str, str],
        ) -> Tuple[Iterator[dict], dict]:
            """
            Read geocoding search results.

            Args:
                config: Table configuration
                table_options: Additional options including:
                    - name (required): Location name to search for
                    - count (optional): Number of results to return (default: 10)
                    - language (optional): Language for results (default: en)

            Returns:
                Tuple of (iterator of records, next offset)
            """
            # Get search parameters from table_options
            name = table_options.get("name")
            if not name:
                raise ValueError("'name' parameter is required for geocoding table")

            count = int(table_options.get("count", config.get("default_count", 10)))
            language = table_options.get("language", "en")

            # Build API parameters
            params = {
                "name": name,
                "count": count,
                "language": language,
                "format": "json",
            }

            # Add API key if commercial
            if self.api_key:
                params["apikey"] = self.api_key

            # Make API request
            url = f"{self.geocoding_base_url}/{config['endpoint']}"
            data = self._make_request(url, params)

            # Process results
            results = data.get("results", [])

            def generate_geocoding_records() -> Iterator[dict]:
                """Generate geocoding records from API response."""
                for result in results:
                    yield {
                        "id": result.get("id"),
                        "name": result.get("name"),
                        "latitude": result.get("latitude"),
                        "longitude": result.get("longitude"),
                        "elevation": result.get("elevation"),
                        "feature_code": result.get("feature_code"),
                        "country_code": result.get("country_code"),
                        "country": result.get("country"),
                        "admin1": result.get("admin1"),
                        "admin2": result.get("admin2"),
                        "admin3": result.get("admin3"),
                        "admin4": result.get("admin4"),
                        "timezone": result.get("timezone"),
                        "population": result.get("population"),
                        "postcodes": result.get("postcodes"),
                    }

            # For geocoding (snapshot), return empty offset
            next_offset = {}

            return generate_geocoding_records(), next_offset

        def _generate_records(self, data: Dict[str, Any], data_key: str) -> Iterator[dict]:
            """
            Generate records from API response.

            Args:
                data: API response dictionary or list of dictionaries
                data_key: Key to extract data from (e.g., "hourly", "daily")

            Yields:
                Dictionary records with latitude, longitude, time, and all variables
            """
            # Handle case where API returns a list of location responses
            if isinstance(data, list):
                for location_data in data:
                    yield from self._generate_records_from_single_location(location_data, data_key)
            else:
                # Single location response
                yield from self._generate_records_from_single_location(data, data_key)

        def _generate_records_from_single_location(
            self, data: Dict[str, Any], data_key: str
        ) -> Iterator[dict]:
            """
            Generate records from a single location's API response.

            Args:
                data: API response dictionary for a single location
                data_key: Key to extract data from (e.g., "hourly", "daily")

            Yields:
                Dictionary records with latitude, longitude, time, and all variables
            """
            # Handle both single location (scalar) and multi-location (array) responses
            lat = data.get("latitude")
            lon = data.get("longitude")

            # Check if latitude/longitude are arrays (multi-location) or scalars (single location)
            is_multi_location = isinstance(lat, list)

            time_series_data = data.get(data_key, {})
            times = time_series_data.get("time", [])

            for i, time_value in enumerate(times):
                # For multi-location, use arrays; for single location, use scalar
                if is_multi_location:
                    # Multi-location: lat/lon are at same index as time
                    record = {
                        "latitude": lat[i] if i < len(lat) else None,
                        "longitude": lon[i] if i < len(lon) else None,
                        "time": time_value,
                    }
                else:
                    # Single location: lat/lon are scalars
                    record = {
                        "latitude": lat,
                        "longitude": lon,
                        "time": time_value,
                    }

                # Add all variables from the response
                for key, values in time_series_data.items():
                    if key != "time" and i < len(values):
                        record[key] = values[i]

                yield record


    ########################################################
    # pipeline/lakeflow_python_source.py
    ########################################################

    METADATA_TABLE = "_lakeflow_metadata"
    TABLE_NAME = "tableName"
    TABLE_NAME_LIST = "tableNameList"
    TABLE_CONFIGS = "tableConfigs"
    IS_DELETE_FLOW = "isDeleteFlow"


    class LakeflowStreamReader(SimpleDataSourceStreamReader):
        """
        Implements a data source stream reader for Lakeflow Connect.
        Currently, only the simpleStreamReader is implemented, which uses a
        more generic protocol suitable for most data sources that support
        incremental loading.
        """

        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.lakeflow_connect = lakeflow_connect
            self.schema = schema

        def initialOffset(self):
            return {}

        def read(self, start: dict) -> (Iterator[tuple], dict):
            is_delete_flow = self.options.get(IS_DELETE_FLOW) == "true"
            # Strip delete flow options before passing to connector
            table_options = {
                k: v for k, v in self.options.items() if k != IS_DELETE_FLOW
            }

            if is_delete_flow:
                records, offset = self.lakeflow_connect.read_table_deletes(
                    self.options[TABLE_NAME], start, table_options
                )
            else:
                records, offset = self.lakeflow_connect.read_table(
                    self.options[TABLE_NAME], start, table_options
                )
            rows = map(lambda x: parse_value(x, self.schema), records)
            return rows, offset

        def readBetweenOffsets(self, start: dict, end: dict) -> Iterator[tuple]:
            # TODO: This does not ensure the records returned are identical across repeated calls.
            # For append-only tables, the data source must guarantee that reading from the same
            # start offset will always yield the same set of records.
            # For tables ingested as incremental CDC, it is only necessary that no new changes
            # are missed in the returned records.
            return self.read(start)[0]


    class LakeflowBatchReader(DataSourceReader):
        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.schema = schema
            self.lakeflow_connect = lakeflow_connect
            self.table_name = options[TABLE_NAME]

        def read(self, partition):
            all_records = []
            if self.table_name == METADATA_TABLE:
                all_records = self._read_table_metadata()
            else:
                all_records, _ = self.lakeflow_connect.read_table(
                    self.table_name, None, self.options
                )

            rows = map(lambda x: parse_value(x, self.schema), all_records)
            return iter(rows)

        def _read_table_metadata(self):
            table_name_list = self.options.get(TABLE_NAME_LIST, "")
            table_names = [o.strip() for o in table_name_list.split(",") if o.strip()]
            all_records = []
            table_configs = json.loads(self.options.get(TABLE_CONFIGS, "{}"))
            for table in table_names:
                metadata = self.lakeflow_connect.read_table_metadata(
                    table, table_configs.get(table, {})
                )
                all_records.append({TABLE_NAME: table, **metadata})
            return all_records


    class LakeflowSource(DataSource):
        def __init__(self, options):
            self.options = options
            self.lakeflow_connect = LakeflowConnect(options)

        @classmethod
        def name(cls):
            return "lakeflow_connect"

        def schema(self):
            table = self.options[TABLE_NAME]
            if table == METADATA_TABLE:
                return StructType(
                    [
                        StructField(TABLE_NAME, StringType(), False),
                        StructField("primary_keys", ArrayType(StringType()), True),
                        StructField("cursor_field", StringType(), True),
                        StructField("ingestion_type", StringType(), True),
                    ]
                )
            else:
                # Assuming the LakeflowConnect interface uses get_table_schema, not get_table_details
                return self.lakeflow_connect.get_table_schema(table, self.options)

        def reader(self, schema: StructType):
            return LakeflowBatchReader(self.options, schema, self.lakeflow_connect)

        def simpleStreamReader(self, schema: StructType):
            return LakeflowStreamReader(self.options, schema, self.lakeflow_connect)


    spark.dataSource.register(LakeflowSource)  # pylint: disable=undefined-variable
